### DISCUSSION TITLE
How to change/add field templates

### DISCUSSION THREAD

**Discussion by valentin-** [dachcom-digital/pimcore-formbuilder#358] [General]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi, 

I'd like to set the width of fields and thought this could be done using a custom template. Unfortunately theres nothing described in the documentation and i couldn't figure out how to define those templates or what they are used for.

Could you give me more information on this?

![image](https://user-images.githubusercontent.com/90033/188472365-7feeb654-ed99-4628-965f-6471e6b8d0d2.png)

Thanks!

**Comment by valentin-** [comment]
Now I've found this thread.

https://talk.pimcore.org/t/dachcom-formbuilder-how-to-populate-template-field/2265/2

Could you give me an example how you use this setting? I was expecting a real template, not a data attribute.

![image](https://user-images.githubusercontent.com/90033/188475006-24e09982-26f0-4b77-8eb8-62ad2f3ea1db.png)

**Comment by solverat** [comment]
Since this is not an issue, I moved this to the discussion section.

You're on the right track:

```yaml
form_builder:
    form:
        field:
            templates:
                full:
                    value: 'col-12'
                    label: 'form_builder_type_template.full'
                    default: true
                half:
                    value: 'col-6'
                    label: 'form_builder_type_template.half'
                    default: false
```
Also, please make sure you're using a formbuilder form theme in your template. If you're using forms via bricks, you're able to select the layout here:

![image](https://user-images.githubusercontent.com/700119/202215082-6151c4fb-e336-4669-b85d-02aad55e791f.png)
