### DISCUSSION TITLE
Custom form theme

### DISCUSSION THREAD

**Discussion by abdellahrk** [dachcom-digital/pimcore-formbuilder#469] [Q&A]
Hello, I am unable to use a custom theme since I am using Tailwind and want to override every field.
I get this error 
```
Unable to find template "@FormBuilder/form/theme/macro/demo_form_theme.html.twig" (looked into: 
/var/www/html/templates/bundles/FormBuilderBundle, /var/www/html/vendor/dachcom-digital/formbuilder/templates) in 
[@FormBuilder/form/form.html.twig at line 4](file://%40formbuilder/form/form.html.twig#L4).'
``` 
when I extend the bootstrap layout with `{% extends "@!FormBuilder/form/theme/bootstrap_4_horizontal_layout.html.twig" %}` 
And this is how I am rendering it 
``` 
{% set form = {
                'form_id': 1,
                'form_template': 'demo_form_theme.html.twig'
            } %}
                {{ form_builder_static(form) }}
```
 Thanks in advance.

**Comment by solverat** [comment]
Hey @abdellahrk 

```yaml
form_builder:
    form:
        templates:
            form_div_layout: ~  #disable other form layouts, if you want
            bootstrap_3_layout: ~
            bootstrap_3_horizontal_layout: ~
            bootstrap_4_layout: ~
            bootstrap_4_horizontal_layout: ~
            tailwind_2_layout:
                value: 'tailwind_2_layout.html.twig'
                label: 'Tailwind'
                default: true
```
Then you've to create your theme layout here: 

`app/templates/bundles/FormBuilderBundle/form/theme/tailwind_2_layout.html.twig`

```twig
{% extends 'tailwind_2_layout.html.twig' %} {# use the symfony tailwind base layout  #}

{% use '@FormBuilder/form/theme/type/dynamic_multi_file.html.twig' %}
{% use '@FormBuilder/form/theme/type/html_tag.html.twig' %}
{% use '@FormBuilder/form/theme/type/snippet.html.twig' %}
{% use '@FormBuilder/form/theme/type/container.html.twig' %}

{%- block form_widget_compound -%}
  {# your overrides #}
{%- endblock form_widget_compound -%}

{% block checkbox_label -%}
    {# your overrides #}
{%- endblock checkbox_label %}

{# more overrides #}
```
and finally you're able to select this layout within the form area brick or if you want to place it manually:

```twig
{% set config = {
    form_id: 123,
    form_template: 'tailwind_2_layout.html.twig',
    output_workflow: 'default'
} %}

{{ form_builder_static(config) }}
```
