### ISSUE TITLE
Constraint Restriction Selection for Fields

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-formbuilder#132]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Currently it's only possible do enable/disable contraints. We should allow to define allowed/disallowed constraints for each form field, for example:

```yml
form_builder:
    types:
        dynamic_multi_file:
            backend:
                constraints:
                    - email
```
