### ISSUE TITLE
FineUploader is deprecated

### ISSUE THREAD

**Issue by patric-eberle** [dachcom-digital/pimcore-formbuilder#261]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

The used JS plugin FineUploader for the file upload is no longer maintained and requires HTML which is not W3C conform (e.g. attributes on elements for translations and identification). It should be replaced with a modern Alternative.

**Comment by dennistiboni-extera** [comment]
Hi @solverat ,
do you have an estimated release date for the new uploader?

Regards

**Comment by solverat** [comment]
## To-Do
- downgrade FineUploader as hard coded default uploader 
- introduce DynamicMultifileAdapter via symfony tag `form_builder.dynamic_multi_file.adapter`
- create dedicated javascript handler for each adapter
- load js handler (and libraries) asynchronously 
- remove session storage and use hidden field instead
- keep FineUploader as default in 3.4
- introduce DropZone as an additional Adapter

## Configuration Example
```yaml
forbmuilder:
services:
    FormBuilderBundle\DynamicMultiFile\Adapter\FineUploadAdapter:
        tags:
            - { name: form_builder.dynamic_multi_file.adapter }

form_builder:
    dynamic_multi_file_adapter: FormBuilderBundle\DynamicMultiFile\Adapter\FineUploadAdapter
```

## Deprecation in 3.4 and breaking changes in 4.0 
- move resource `vendor/fineuploader/*` to `plugins/dynamic-multi-file/vendor/*` in `4.0`
- dmf handler + vendor are now fetched asynchronously (and only if upload fields are available/required) to minimize the js stack on each request
