### ISSUE TITLE
[FormBuilder2] Tag Field

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-formbuilder#56]
create a custom form type for some simple html elements:

```yaml
parameters:
     tag_field_types:
          - h1
          - h2
          - h3
          - p
          - span
          - label
```
 
this will generate a valid form element, for example:

```twig
<h3>field label</h3>
```
