### ISSUE TITLE
Adding more validators by default and configurable ones

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-formbuilder#73]
By default, formbuilder is installed with two validators: not blank and email.
Maybe, more could be added by default, at least the more used (regex, date, url, greaterThan, lessThan, range, etc.) ?

Documentation don't seems to explain how to add validators, maybe some hints could be added ?

I manage to do it by editing https://github.com/dachcom-digital/pimcore-formbuilder/blob/master/src/FormBuilderBundle/Resources/config/backend/base_config.yml and adding at the end, based on https://github.com/symfony/symfony/tree/3.4/src/Symfony/Component/Validator/Constraints:

```
        url:
            class: Symfony\Component\Validator\Constraints\Url
            label: 'form_builder_validation_constraint.url'
            icon_class: form_builder_icon_validation
        regex:
            class: Symfony\Component\Validator\Constraints\Regex
            label: 'form_builder_validation_constraint.regex'
            icon_class: form_builder_icon_validation
```

Problem is that for the second one, regex pattern should be configurable. But opening the validator tab just display:

![image](https://user-images.githubusercontent.com/9025839/34320689-0b3dafe0-e800-11e7-89b8-0bac0600188a.png)

Maybe it should be detected that this validator needs options to be configured and in this case add options fields on this validator tab ?
Or maybe i missed something about installing new validtors ?

Thanks! I love this extension : )))
